language: python
python:
- 3.7
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  skip_existing: true
  distributions: sdist bdist_wheel
  user: giswqs
  password:
    secure: ASv050Qm76aXgf1HrrjOZDp/1BBkQJSsB5SbHiJkKdCDFYK5NMF5VGDxRl3rdEJQDHwIr0wYpumEmVlSnQJgAWwWw8ufDI9cUo5rnOUjTRLkOxw0Qekzu2X05HPCa20bYDvnXRK1qCuzAr0tekrIAc6GTz4V08Yt20AQK+CF4bgSHhNwsPMa02LVZO0rLfQJILPnzfSMRigGlTFnRtL5roeS/oLeWQcA7iFpcvOgQEy+Ay1bw3V0JKnK9NKbqQvo3eyYuD+NhqOow/gZLWXcYqBxPziWEFYXJJasl1z8YRchzE7PMeOtLzfO8MMxW+vxcn45wQWm1z9OOrKu7lVRJ2BNpxPwNRqfQAGqrroqAx5u/PLwxULJjrkwoY92cyY91jLFPjswPVMoTuHm5C0MCS50XUAQjTx5s2cWVrblndJQMG1mAkxqek3IQ6IYTGnpHNh43OOLKlPQdufejbcCHYByVAprAxiKNl3JTAEdpe6+13fzlhvvmXMUaIbT1mWufvwaCF/HRU5YHXVkf9CNiHUEzmS2NRYpSnroeAFW0d0ScPX7xRxfkagiFVI2QNPZqXhzJVYJdWvptVhMnA32bqFhOq17RFxkY37HIlcTf6Mpty6cTm5eUAclKJyv1qyzoIrl9oihzr3n7R4pA+z+fhBuLEmeDYjsaLwdzylP93U=
  on:
    tags: true
    repo: giswqs/whitebox
    python: 3.7